### ISSUE TITLE
PG-Build API with Basic auth no longer working

### ISSUE THREAD

**Issue by DURK** [chrisprice/phonegap-build#18]
A few weeks ago, they've <a href="http://phonegap.com/blog/2014/04/16/removing-legacy-logins/">announced</a> deprecating basic auth for the API.

It seems they have some strange definition of <i>"rest assured we will give adequate notice"</i>, because as of today it doesn't seem to work:
```
[INFO] AuthChallengeProcessor - -basic authentication scheme selected
[INFO] HttpMethodDirector - -Failure authenticating with BASIC 'Application'@build.phonegap.com:443
[JENKINS] Archiving disabled
```

This means the maven-plugin should be adjusted to collect and use an API-token.

As you can see, this makes our Jenkins builds unstable, so me or one of my colleagues will most likely fix this and submit a pull-request shortly :)

**Comment by chrisprice** [comment]
Going to assume this isn't an issue anymore...
