### ISSUE TITLE
Delete signing key after build.

### ISSUE THREAD

**Issue by ebostijancic** [chrisprice/phonegap-build#20]
If building a lot, the signing keys section has a huge list of singing keys, therefore the key used for the build should be deleted after a successful build.

**Comment by chrisprice** [comment]
Hipes this is an old issue...

If you're still looking for a solution to this, you can achieve this functionality by binding the clean/scorch goal appropriately. For more details see this [comment](https://github.com/chrisprice/phonegap-build/pull/23#issuecomment-92095630).
